# Generated by Django 4.2.2 on 2023-08-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_remove_wishlist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
