# Generated by Django 4.2.2 on 2023-07-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shippingaddress_default_address_and_more'),
        ('cart', '0003_order_order_status_order_payment_type_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.shippingaddress'),
        ),
    ]
