# Generated by Django 4.2.2 on 2023-07-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_orderdetail_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_status',
            field=models.CharField(choices=[('order_pending', 'Order_Pending'), ('order_confirmed', 'Order_Confirmed'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='order_pending', max_length=100),
        ),
    ]
