# Generated by Django 4.2.2 on 2023-07-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_orderdetail_is_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='is_cancelled',
            new_name='is_returned',
        ),
    ]
