# Generated by Django 4.2.2 on 2023-07-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_razor_pay_order_id_cart_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='offer_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
