# Generated by Django 4.2.2 on 2023-07-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_offer_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='offer_total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razor_pay_payment_signature',
        ),
    ]
