# Generated by Django 4.2.2 on 2023-07-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_cart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
    ]
