# Generated by Django 4.2.2 on 2023-07-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_cart_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
