# Generated by Django 4.2.2 on 2023-08-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
