# Generated by Django 4.2.2 on 2023-08-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_orderdetail_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
