# Generated by Django 4.2.2 on 2023-08-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_alter_coupons_options_alter_usedcoupons_options'),
        ('cart', '0019_remove_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.coupons'),
        ),
    ]
