# Generated by Django 4.2.2 on 2023-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='categories_images/61f-Do0Z-aL._SX679_.jpg', upload_to='product_images'),
        ),
    ]
