# Generated by Django 4.2.2 on 2023-07-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_color_remove_product_price_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
