# Generated by Django 4.2.2 on 2023-07-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productimage_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
