# Generated by Django 4.2.2 on 2023-07-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='color',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
