# Generated by Django 4.2.2 on 2023-07-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_variant_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='color',
            new_name='colour',
        ),
    ]
