# Generated by Django 4.2.2 on 2023-07-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rename_color_variant_colour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='order',
        ),
    ]
