# Generated by Django 4.2.2 on 2023-07-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_productimage_color_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
