# Generated by Django 4.2.2 on 2023-07-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_variant_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='offer_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
