# Generated by Django 4.2.2 on 2023-07-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_variant_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='offer_price',
        ),
    ]
