# Generated by Django 4.2.2 on 2023-07-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_variant_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
