# Generated by Django 4.2.2 on 2023-07-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_variant_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
