# Generated by Django 4.2.1 on 2023-08-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shippingaddress_default_address_and_more'),
        ('products', '0035_category_created_at_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPurchasedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('variants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variant')),
            ],
            options={
                'verbose_name_plural': 'User purchased products',
            },
        ),
    ]
