# Generated by Django 4.2.1 on 2023-08-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_userpurchasedproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPurchasedProducts',
        ),
    ]
