# Generated by Django 4.2.1 on 2023-08-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_userpurchasedproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpurchasedproducts',
            name='variants',
        ),
    ]
