# Generated by Django 4.2.1 on 2023-08-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_remove_userpurchasedproducts_variants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPurchasedProducts',
        ),
    ]
