# Generated by Django 4.2.2 on 2023-07-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
