# Generated by Django 4.2.2 on 2023-07-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offers_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
