# Generated by Django 4.2.2 on 2023-08-02 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_offers_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
