# Generated by Django 4.2.2 on 2023-08-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
