# Generated by Django 4.2.2 on 2023-08-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_alter_coupons_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupons',
        ),
    ]
