# Generated by Django 4.2.2 on 2023-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_usedcoupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
