# Generated by Django 4.2.2 on 2023-08-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_coupons_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='valid_to',
            field=models.DateField(),
        ),
    ]
