# Generated by Django 4.2.1 on 2023-08-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviews_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='variant',
        ),
    ]
