# Generated by Django 4.2.1 on 2023-08-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_reviews_variant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
